# Generated by Django 2.2.5 on 2019-09-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('content_id', models.CharField(max_length=255)),
                ('episode_number', models.CharField(db_column='episod_id', max_length=50)),
                ('hosted_by', models.CharField(db_column='hosting', max_length=50)),
                ('thumbnail', models.CharField(max_length=50)),
                ('audio_id', models.CharField(max_length=255)),
                ('embed_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('duration', models.IntegerField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('documentary_type', models.CharField(max_length=50)),
                ('publication_date', models.DateTimeField()),
                ('fact_check', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'imago_info_video',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagoCornerContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corner_id', models.CharField(max_length=50)),
                ('content_order', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('content_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'imago_corner_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagoHomeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('sub_type', models.CharField(max_length=50)),
                ('folder_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('query_id', models.CharField(max_length=50)),
                ('href', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'imago_home_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('env', models.CharField(max_length=50)),
                ('content_id', models.CharField(max_length=50)),
                ('ppv', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1024)),
                ('link', models.CharField(max_length=255)),
                ('date', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=50)),
                ('note_1', models.IntegerField()),
                ('note_number_1', models.IntegerField()),
                ('note_2', models.IntegerField()),
                ('note_number_2', models.IntegerField()),
                ('note_3', models.IntegerField()),
                ('note_number_3', models.IntegerField()),
                ('hostin', models.CharField(max_length=50)),
                ('thumbnai', models.CharField(max_length=50)),
                ('video_number', models.IntegerField()),
                ('dvd', models.CharField(max_length=255)),
                ('vod', models.CharField(max_length=255)),
                ('crowdfunding', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=512)),
                ('season_size', models.CharField(max_length=50)),
                ('rss', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'imago_info_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagoInfoCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('creator_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'imago_info_creator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagoListMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('subscription_date', models.DateTimeField()),
                ('modification_date', models.DateTimeField()),
                ('note_1', models.IntegerField()),
                ('note_2', models.IntegerField()),
                ('note_3', models.IntegerField()),
                ('note_4', models.IntegerField()),
                ('note_5', models.IntegerField()),
                ('note_6', models.IntegerField()),
                ('note_7', models.IntegerField()),
                ('note_8', models.IntegerField()),
            ],
            options={
                'db_table': 'imago_list_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagoMyDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('content_id', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('donation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'imago_my_donation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagoMyFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('content_id', models.CharField(max_length=255)),
                ('episod_id', models.IntegerField()),
                ('add_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'imago_my_favorite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagoMyFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_1', models.IntegerField()),
                ('user_id_2', models.IntegerField()),
                ('invitation_date', models.DateTimeField()),
                ('acceptance_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'imago_my_friend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagoMyLater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('content_id', models.CharField(max_length=255)),
                ('episod_id', models.IntegerField()),
                ('add_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'imago_my_later',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagoRelatedAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=50)),
                ('author_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'imago_related_author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagoRelatedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=1024)),
                ('color', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=255)),
                ('add_date', models.DateTimeField()),
                ('vote', models.IntegerField()),
                ('liked', models.IntegerField()),
                ('warning', models.IntegerField()),
            ],
            options={
                'db_table': 'imago_related_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagoRelatedQuizz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=1024)),
                ('timecode', models.TimeField()),
                ('user_id', models.CharField(max_length=255)),
                ('add_date', models.DateTimeField()),
                ('answer_1', models.CharField(max_length=50)),
                ('answer_2', models.CharField(max_length=50)),
                ('answer_3', models.CharField(max_length=50)),
                ('answer_4', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'imago_related_quizz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagoTagScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('screen_id', models.CharField(max_length=50)),
                ('type_id', models.CharField(max_length=50)),
                ('category_id', models.CharField(max_length=50)),
                ('content_id', models.CharField(max_length=50)),
                ('video_id', models.CharField(max_length=255)),
                ('section_id', models.CharField(max_length=50)),
                ('episod_id', models.CharField(max_length=50)),
                ('view', models.IntegerField()),
            ],
            options={
                'db_table': 'imago_tag_screen',
                'managed': False,
            },
        ),
    ]
